### ISSUE TITLE
Hyprpaper does nothing on NixOS

### ISSUE THREAD

**Issue by WilliamBehrens** [hyprwm/hyprpaper#67] opened 2023-04-27 14:59 UTC
wallpaper.jpg does exist
`hyprpaper.conf`
```
preload = ~/media/pictures/wallpaper.jpg

# Set the default wallpaper seen on inital workspace(s)
wallpaper = , ~/media/pictures/wallpaper.jpg
```

I've installed on nixos using flakes but running the `hyprpaper` command with the above config does nothing.

```
[LOG] Welcome to hyprpaper!
built from commit 9182de9ffc8c76fbf24d16dec0ea7a9430597a06 ()
[LOG] Cleaned old hyprpaper preloads (3), removing 40.7MB
[LOG] Preloaded target /home/will/media/pictures/wallpaper.jpg in 73.48ms -> Pixel size: [3840, 2160]
[LOG] hyprpaper socket started at /tmp/hypr/f23455e592bca14e0abd9249de467cc71cd2850e_1682607044/.hyprpaper.sock (fd: 4)
[LOG] configure for eDP-1
[LOG] handlePreferredScale: 1.65 for 17796b0
[LOG] Buffer created for target /home/will/media/pictures/wallpaper.jpg, Shared Memory usage: 13.6MB
[LOG] Total SM usage for all buffers: 13.6MB
[LOG] Pool buffer missing for available target??
[LOG] Buffer created for target /home/will/media/pictures/wallpaper.jpg, Shared Memory usage: 13.6MB
[LOG] Total SM usage for all buffers: 27.1MB
[LOG] Pool buffer failed #2. Ignoring WP.
[LOG] handlePreferredScale: 1.65 for 17796b0
[LOG] Buffer created for target /home/will/media/pictures/wallpaper.jpg, Shared Memory usage: 13.6MB
[LOG] Total SM usage for all buffers: 40.7MB
```
but the wallpaper doesn't change

**Comment by vaxerski** [comment] 2023-04-27 21:56
`wallpaper = , ~/media/pictures/wallpaper.jpg` -> `wallpaper = ,~/media/pictures/wallpaper.jpg`

hyprpaper does not allow spaces in args

**Comment by WilliamBehrens** [comment] 2023-04-28 17:55
The wallpaper is appearing now but then hyprpaper immediately segfaults. 
```
[LOG] Welcome to hyprpaper!
built from commit 9182de9ffc8c76fbf24d16dec0ea7a9430597a06 ()
[LOG] Cleaned old hyprpaper preloads (3), removing 43.0MB
[LOG] Preloaded target /home/will/media/pictures/wallpaper.jpg in 27.72ms -> Pixel size: [3840, 2160]
[LOG] hyprpaper socket started at /tmp/hypr/f23455e592bca14e0abd9249de467cc71cd2850e_1682703548/.hyprpaper.sock (fd: 4)
[LOG] configure for DP-5
[LOG] handlePreferredScale: 1.00 for 46da00
[LOG] handlePreferredScale: 1.00 for 46da00
[LOG] Buffer created for target /home/will/media/pictures/wallpaper.jpg, Shared Memory usage: 14.7MB
[LOG] Total SM usage for all buffers: 14.7MB
[LOG] Image data for DP-5: /home/will/media/pictures/wallpaper.jpg at [-0.00, 0.00], scale: 0.67 (original image size: [3840, 2160])
[LOG] Submitting viewport dest size 2560x1440 for 46da00
[LOG] configure for DP-6
[LOG] handlePreferredScale: 1.00 for 46d920
[LOG] handlePreferredScale: 1.00 for 46d920
[LOG] configure for eDP-1
[LOG] handlePreferredScale: 1.65 for 46d530
[LOG] Buffer created for target /home/will/media/pictures/wallpaper.jpg, Shared Memory usage: 14.7MB
[LOG] Buffer created for target /home/will/media/pictures/wallpaper.jpg, Shared Memory usage: 13.6MB
[LOG] Total SM usage for all buffers: 43.0MB
[LOG] Image data for DP-6: /home/will/media/pictures/wallpaper.jpg at [-1312.50, 0.00], scale: 1.19 (original image size: [3840, 2160])
[LOG] Submitting viewport dest size 1440x2560 for 46d920
zsh: segmentation fault (core dumped)  hyprpaper
```

**Comment by vaxerski** [comment] 2023-04-29 12:23
that one is a dupe of #51 and is fixed in -git.

**Closed by vaxerski** 2023-04-29 12:23 UTC

**Comment by WilliamBehrens** [comment] 2023-04-29 15:02
I'm not familiar with using the `-git` version on nix, is that the same as https://wiki.hyprland.org/Nix/Hyprland-on-NixOS/#using-unstable-hyprland ?
